name: CI

on: [push, pull_request, workflow_dispatch]
env:
  ARCH: x86_64
  CC: gcc

jobs:
  Documentation:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install asciidoctor mscgen graphviz doxygen
        sudo apt-get install libconfig-dev
    - name: Build
      run: ./scripts/build.sh -d

  Build-bionic-gcc:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install automake autoconf libconfig-dev libssl-dev libtool pkg-config hugepages
    - name: Build
      run: ./scripts/build.sh

  Run-bionic_gcc:
    runs-on: ubuntu-18.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install automake autoconf libconfig-dev libssl-dev libtool pkg-config hugepages
        sudo pip3 install robotframework
    - name: Checkout EM-ODP
      uses: actions/checkout@v2
    - name: Checkout ci
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository_owner }}/ci
        clean: false
        path: ci
        ref: clean-up
    - name: Build EM-ODP
      run: ./scripts/build.sh
    - name: Run Robot Tests
      run: |
        sudo sysctl -w vm.nr_hugepages=512
        cat /proc/meminfo | grep Huge
        ./ci/test.sh

  Build-focal_gcc:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install automake autoconf libconfig-dev libssl-dev libtool pkg-config
    - name: Build
      run: |
        git clone https://github.com/openeventmachine/ci.git
        echo "./scripts/build.sh" >> ci/docker.sh
        sudo docker run --privileged --name focal -i -v /dev/hugepages:/dev/hugepages -v ${PWD}:/root/em-odp -w /root/em-odp --shm-size 4g ubuntu:20.04 sh ci/docker.sh

  Build-focal_clang:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install automake autoconf libconfig-dev libssl-dev libtool pkg-config
    - name: Build
      run: |
        git clone https://github.com/openeventmachine/ci.git
        echo "apt remove gcc -y" >> ci/docker.sh
        echo "apt install clang -y" >> ci/docker.sh
        echo "./scripts/build.sh" >> ci/docker.sh
        sudo docker run --privileged --name focal -i -v /dev/hugepages:/dev/hugepages -v ${PWD}:/root/em-odp -w /root/em-odp --shm-size 4g ubuntu:20.04 sh ci/docker.sh
